[tool.poetry]
name = "course-work-4-oop"
version = "0.1.0"
description = ""
authors = ["Vladimir Pristansky <pristanskyvs@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
